# Site settings
title: "Intuitív barangolások, Költészet és Filozófia"
author: "Ejderha"
description: "Az igazság alapjától fogva inkompatibilis a létezéssel"
keywords: "Költészet, Filozófia, Idealizmus, Materializmus, Fizikalizmus, Nondualitás, Védikus, Zen, Tudat, Mesterséges Intelligencia, Halál, Isten"
biography: "A bölcsesség szerelmese vagyok, szégyentelen promiszkuitásban élek a világnézetemet tágító gondolatokkal. Az itt megjelenő írások fő célja, a mai világunkban uralkodó materialista, fizikalista világnézet fölösleges szenvedtető uralmát megdönteni filozófiai alapokon és egy tágabb világnézet felé adni meghívást."
colophon: "© MMXIII — MMXX by Hugo Sereno Ferreira.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/''>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/''>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a> and <a href='http://getbootstrap.com'>Bootstrap</a>."

baseurl: ""
url: "http://ejderhasite.github.io"


facebook_username: ejderha poetry
instagram_username: __ejderha


google-analytics: UA-666666-6

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

gems:
- jekyll-sitemap
