# Site settings
title: "Költészet és Filozófia"
author: "Ejderha"
description: "Az itt megjelenő írások fő célja, a mai világunkban uralkodó materialista világnézet fölösleges szenvedtető uralmát megdönteni filozófiai alapokon és egy tágabb világnézet felé adni meghívást."
keywords: "Költészet, Filozófia, Idealizmus, Materializmus, Fizikalizmus, Nondualitás, Védikus, Zen, Tudat, Mesterséges Intelligencia, Halál, Isten"
biography: "A bölcsesség szerelmese vagyok, szégyentelen promiszkuitásban élek a világnézetemet tágító gondolatokkal."
colophon: "© 2022 Kadlicskó Lőrinc.<br>A tartalom <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/''>Creative Commons (BY-NC-SA)</a> licensz alatt jelenik meg annak visszavonásáig."

baseurl: "ejderhasite.github.io/"
url: "http://ejderhasite.github.io"


facebook_username: ejderha poetry
instagram_username: __ejderha


google-analytics: UA-666666-6

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

gems:
- jekyll-sitemap
